---
name: canary

instance_groups:
- name: canary
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: canary
    release: canary
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: canary
  version: 1.1.3
  url: https://github.com/starkandwayne/canary-boshrelease/releases/download/v1.1.3/canary-1.1.3.tgz
  sha1: 92b4e73f384640fcfac83bd5a43edcfc998788bd
